norm_encode_path = '/Users/sold1/mp3/first lab/weights/e_default.npy'
norm_decode_path = '/Users/sold1/mp3/first lab/weights/d_default.npy'
encode_path = '/Users/sold1/mp3/first lab/weights/e_normalized.npy'
decode_path = '/Users/sold1/mp3/first lab/weights/d_normalized.npy'
images_path = '/Users/sold1/mp3/first lab/img/'
